### PR TITLE
update gemspec to work with Rails 4

### PR DESCRIPTION
**Pull request by isratrade**

### CODE REVIEW

**Comment by unorthodoxgeek** [comment]
@abenari - we need this pull request to be approved and pushed to rubygems.org for foreman to be updated to rails4. can you please give us a hand?

**Comment by unorthodoxgeek** [comment]
Thanks! Lmk when the new version is pused to rubygems.

**Comment by abenari** [comment]
Sure, I'll do that later tonight

**Comment by abenari** [comment]
@unorthodoxgeek, a new version released.

**Pull request merged**
